import cv2
import json
import numpy as np
from pathlib import Path

# Import configurations from previous modules
try:
    from occupancy import PARKING_SPACES
    from detect import INPUT_VIDEO
except ImportError:
    # Fallback defaults if modules are not found in the path
    PARKING_SPACES = {}
    INPUT_VIDEO = "ai/vehicle_detection/data/input.mp4"

# Path for the final rendered output
FINAL_VIDEO_PATH = Path("ai/vehicle_detection/outputs/ASWAN_SMART_CURBS_FINAL.mp4")
# Path to the AI inference results generated by occupancy.py
RESULTS_JSON = Path("ai/vehicle_detection/outputs/occupancy_results.json")

def draw_dashboard(frame, occupancy_info):
    """
    Render a professional UI dashboard at the top of the video frame.
    Displays project branding and real-time occupancy statistics.
    """
    h, w, _ = frame.shape
    
    # Create a semi-transparent black overlay for the header
    overlay = frame.copy()
    cv2.rectangle(overlay, (0, 0), (w, 80), (0, 0, 0), -1)
    
    # Apply alpha blending (60% transparency)
    alpha = 0.6  
    cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0, frame)

    # Render Project Title
    cv2.putText(frame, "ASWAN - SMART CURBS AI SYSTEM", (20, 35), 
                cv2.FONT_HERSHEY_DUPLEX, 0.8, (255, 255, 255), 2)
    
    # Calculate occupancy statistics for the current frame
    total_slots = len(PARKING_SPACES)
    occupied_count = sum(1 for s in occupancy_info.values() if s['status'] == 'Occupied')
    free_count = total_slots - occupied_count
    
    # Render statistics text (Total, Occupied, and Free slots)
    stats_text = f"Total Slots: {total_slots} | Occupied: {occupied_count} | Free: {free_count}"
    cv2.putText(frame, stats_text, (20, 65), 
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 1)

def visualize_system():
    """
    Main visualization engine. Combines the raw video with AI data 
    to produce a high-quality global-standard output.
    """
    # Verify that the AI results file exists before proceeding
    if not RESULTS_JSON.exists():
        print(f"Error: {RESULTS_JSON} not found. Run occupancy.py first!")
        return

    # Load pre-calculated occupancy data
    with open(RESULTS_JSON, 'r') as f:
        all_results = json.load(f)

    # Initialize Video Capture and Metadata
    cap = cv2.VideoCapture(str(INPUT_VIDEO))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 30
    
    # Initialize Video Writer for the final export
    writer = cv2.VideoWriter(str(FINAL_VIDEO_PATH), 
                             cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))

    print(f"Generating Final Global-Standard Video...")

    # Process every frame based on the JSON results
    for frame_data in all_results:
        success, frame = cap.read()
        if not success: 
            break

        # 1. Draw the top monitoring dashboard
        draw_dashboard(frame, frame_data['spaces'])

        # 2. Draw Parking Slots and Vehicle Data
        for space_id, info in frame_data['spaces'].items():
            # Get coordinates for the current parking polygon
            pts = np.array(PARKING_SPACES[int(space_id)], np.int32)
            is_occupied = info['status'] == 'Occupied'
            
            # Color Logic: Red for Occupied, Green for Free
            color = (0, 0, 255) if is_occupied else (0, 255, 0)
            
            # Draw the boundary of the parking space
            cv2.polylines(frame, [pts], True, color, 2)
            
            # Apply a light color tint (wash) to occupied spaces for better visibility
            if is_occupied:
                overlay = frame.copy()
                cv2.fillPoly(overlay, [pts], color)
                # 20% color intensity for the fill
                cv2.addWeighted(overlay, 0.2, frame, 0.8, 0, frame)
                
                # Calculate the center of the polygon to place the Vehicle ID text
                center = np.mean(pts, axis=0).astype(int)
                cv2.putText(frame, f"ID:{info['vehicle_id']}", (center[0]-20, center[1]), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

        # Save the processed frame to the final video file
        writer.write(frame)

    # Release system resources
    cap.release()
    writer.release()
    print(f"SUCCESS! Final visualization saved at: {FINAL_VIDEO_PATH}")

if __name__ == "__main__":
    # Execute the visualization pipeline
    visualize_system()